version: "3.9"

services:
  service:
    build: .
    command: python /api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api
    ports:
      - 8000:8000
    depends_on:
      - db
    entrypoint: /api/entrypoint.sh
  db:
    image: postgres:13
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres_data:
