# Generated by Django 4.1.4 on 2022-12-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Retailer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("vendors", models.ManyToManyField(blank=True, to="api.vendor")),
            ],
        ),
        migrations.CreateModel(
            name="Briefing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("responsible", models.CharField(max_length=200)),
                ("release_date", models.DateField(auto_now_add=True)),
                ("available", models.PositiveSmallIntegerField()),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        serialize=False,
                        to="api.category",
                    ),
                ),
                (
                    "retailer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        serialize=False,
                        to="api.retailer",
                    ),
                ),
            ],
        ),
    ]
